In [1]:
import tensorflow as tf
import os
import numpy as np
import pandas as pd

In [78]:
def process_csv_file(file):
    try:
        csv_data = pd.read_csv(file)
    except:
         print("CANT READ CSV: ", file)
         return
    # print(csv_data.isnull().values.any())
    if csv_data.isnull().values.any():
            print(file)
            return False
    try:
        csv_data = csv_data.drop("class", axis = 1)
    except KeyError:
        pass
    return (csv_data.to_numpy())

In [64]:
file = "/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/train/dog/FNt4N8WFuVY10641_translation_0.5.csv_projective_geo_14_False.csv"
process_csv_file(file)

array([[ 0.02740688, -0.35486283, -1.90647697, ...,  0.16417227,
        -0.09599295,  0.        ],
       [ 0.03286565, -0.35673438, -1.90783131, ...,  0.16135563,
        -0.0943355 ,  0.        ],
       [ 0.02303456, -0.35565996, -1.94184434, ...,  0.15929946,
        -0.08896641,  0.        ],
       ...,
       [ 0.36377377,  0.00391136, -1.15274119, ..., -0.36123698,
         0.        ,  0.        ],
       [ 0.36629457,  0.00540541, -1.19808948, ..., -0.35969363,
         0.        ,  0.        ],
       [ 0.36976547,  0.00584776, -1.28183293, ..., -0.35905882,
         0.        ,  0.        ]])

In [3]:
def set_padding(arr, max_length):
    arr = np.append(arr, np.zeros((max_length-arr.shape[0],300)), axis=0)
    return np.expand_dims(arr, 0)

In [81]:
def prepare_data(folder_path, labels):
    total = 0
    max_length = 0
    # find max length
    for folder in os.listdir(folder_path):
        print(folder)
        if folder != ".DS_Store":
            total += len(os.listdir(os.path.join(folder_path, folder)))
            for file in os.listdir(os.path.join(folder_path, folder)):
                if file != ".DS_Store":
                    data = process_csv_file(os.path.join(folder_path, folder, file))
                    if data is not(False):
                        if data.shape[0] > max_length:
                            max_length = data.shape[0]
    print(max_length)
    # Make the arrays
    X = np.empty((0, max_length, 300))
    Y = np.empty((0,), int)
    print("----------")
    for folder in os.listdir(folder_path):
        print(folder)
        if folder != ".DS_Store":
            for file in os.listdir(os.path.join(folder_path, folder)):
                if file != ".DS_Store":
                    data = process_csv_file(os.path.join(folder_path, folder, file))
                    if data is not(False):
                        data = set_padding(data, max_length)
                        X = np.vstack((X, data))
                        Y = np.append(Y, labels[folder])
    print(total, max_length)
    return X, Y

In [82]:
folder_path_train = "/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/train"
labels= {"coffee": 0, 'dog': 1, 'milk': 2, 'door': 3}
X_train, Y_train = prepare_data(folder_path_train, labels)

.DS_Store
dog
/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/train/dog/lvqGMGFmuV4325_rotation_15_scale_0.2.csv_projective_geo_12_True.csv
/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/train/dog/lvqGMGFmuV4325_rotation_15_translation_0.5_scale_0.2_translate_0.5_left.csv_projective_geo_10_False.csv
/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/train/dog/lvqGMGFmuV4325_rotation_15_translation_0.5_translate_0.5_left.csv_projective_geo_5_False.csv
/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/train/dog/lvqGMGFmuV4325_translation_0.5_scale_0.2_translate_0.5_left.csv_projective_geo_14_True.csv
/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/train

In [83]:
folder_path_test = "/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/test"
labels = {"coffee": 0, 'dog': 1, 'milk': 2, 'door': 3}
X_test, Y_test = prepare_data(folder_path_test, labels)

.DS_Store
dog
milk
coffee
/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/test/coffee/c0tloO5tJUY7125_translation_0.5_scale_0.2.csv_projective_geo_13_False.csv
/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/test/coffee/c0tloO5tJUY7125_translation_0.5_scale_0.2.csv_projective_geo_13_False_REFLECTION_.csv
/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/test/coffee/c0tloO5tJUY7125_translation_0.5_scale_0.2.csv_projective_geo_11_True.csv
/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/test/coffee/c0tloO5tJUY7125_rotation_15_translation_0.5_translate_0.5_left.csv_projective_geo_6_False.csv
/Users/aly/Documents/Programming/Apps/Machine Learning/ASL Converter/data_augmentation/data_four_labels_augmentation/test/coffee/c0

In [13]:
padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
    [
    [711, 632, 71],
    [73, 8, 3215, 55, 927],
    [83, 91, 1, 645, 1253, 927],
], padding="post"
)
# print(X[0][1])
print(((padded_inputs)))

[[ 711  632   71    0    0    0]
 [  73    8 3215   55  927    0]
 [  83   91    1  645 1253  927]]


In [24]:
# Y = np.expand_dims(Y, axis=0)
# Y= Y.T
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [84]:
# shuffle data
from sklearn.utils import shuffle

X_train,Y_train = shuffle(X_train, Y_train, random_state=0)
X_val,Y_val = shuffle(X_test, Y_test, random_state=0)
X_train, Y_train

(array([[[ 4.85883785e-01,  3.14333677e-01, -8.37622702e-01, ...,
           6.77580535e-01, -2.49025412e-03,  0.00000000e+00],
         [ 4.85945836e-01,  3.14508051e-01, -8.91162157e-01, ...,
           6.86340570e-01, -9.96818882e-04,  0.00000000e+00],
         [ 4.85962494e-01,  3.14525247e-01, -9.13868308e-01, ...,
           6.92386508e-01, -7.96751177e-04,  0.00000000e+00],
         ...,
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],
 
        [[ 2.70950828e-02, -7.57456780e-01, -6.52825356e-01, ...,
           1.81717188e-01, -2.50094254e-02,  0.00000000e+00],
         [ 2.42124753e-02, -7.52006778e-01, -5.87149799e-01, ...,
           1.51469481

In [85]:
X_train.shape, Y_train.shape

((11060, 211, 300), (11060,))

In [86]:
x_shape = X_train.shape

In [87]:
from tensorflow.keras import layers
masking_input = []
for i in range(x_shape[0]):
    masking_input.append(X_train[i].T[0])

masking_input = np.array(masking_input)

masking_input.shape

(11060, 211)

In [20]:
embedding = layers.Embedding(input_dim=x_shape[1], output_dim=x_shape[1], mask_zero=True)
masked_output = embedding(masking_input)

print(masked_output._keras_mask)
masked_output
# masking_layer = layers.Masking()
# # Simulate the embedding lookup by expanding the 2D input to 3D,
# # with embedding dimension of 10.
# unmasked_embedding = tf.cast(
#     tf.tile(tf.expand_dims(padded_inputs, axis=-1), [1, 1, 10]), tf.float32
# )

# masked_embedding = masking_layer(unmasked_embedding)
# print(masked_embedding._keras_mask)

2023-04-21 00:13:36.221629: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-04-21 00:13:36.222041: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

tf.Tensor(
[[ True  True  True ... False False False]
 [ True  True  True ... False False False]
 [ True  True  True ... False False False]
 ...
 [ True  True  True ... False False False]
 [ True  True  True ... False False False]
 [ True  True  True ... False False False]], shape=(457, 211), dtype=bool)


<tf.Tensor: shape=(457, 211, 211), dtype=float32, numpy=
array([[[ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        ...,
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526]],

       [[ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        ..

In [90]:
#LSTM model 
from tensorflow.keras import layers
x_shape = (457, 211, 300)
inputs = layers.Input(shape=(x_shape[1], x_shape[2]))
x = layers.Masking(mask_value=0, input_shape=(x_shape[1], x_shape[2]))(inputs)
#return_sequences makes so that we can stack lstm layers together. Since the input shape of lstm is different
x = layers.LSTM(64, return_sequences = True)(x)
x = layers.LSTM(32, return_sequences = True)(x)
x = layers.Dense(64)(x)
# x = layers.MaxPool2D()(x)
outputs = layers.Dense(4, activation="softmax")(x)

model_lstm = tf.keras.Model(inputs, outputs)
model_lstm.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 211, 300)]        0         
                                                                 
 masking_1 (Masking)         (None, 211, 300)          0         
                                                                 
 lstm_2 (LSTM)               (None, 211, 64)           93440     
                                                                 
 lstm_3 (LSTM)               (None, 32)                12416     
                                                                 
 dense_2 (Dense)             (None, 64)                2112      
                                                                 
 dense_3 (Dense)             (None, 4)                 260       
                                                                 
Total params: 108,228
Trainable params: 108,228
Non-trainab

In [92]:
model_lstm.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model_lstm.fit(X_train, Y_train, epochs=50, validation_data=(X_val, Y_val))

Epoch 1/50


2023-05-16 07:19:40.722082: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-05-16 07:19:42.567144: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-05-16 07:19:48.025183: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-05-16 07:19:53.578057: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-05-16 07:21:11.596147: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


 10/346 [..............................] - ETA: 3:22 - loss: 1.3942 - accuracy: 0.2594

In [47]:
def get_mask_from_lengths(data):  #2d list
    ids = tf.zeros(shape=(x_shape[1], x_shape[2]))
    all_zeros = ids < data
    mask_list = []
    for i in range()
    return mask

get_mask_from_lengths(X_train)[0]

<tf.Tensor: shape=(211, 300), dtype=bool, numpy=
array([[ True,  True, False, ...,  True, False, False],
       [ True,  True, False, ...,  True, False, False],
       [ True,  True, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])>

In [48]:
inputs = layers.Input(shape=(x_shape[1], x_shape[2]))
x = layers.GRU(64)(inputs, mask=masked_output._keras_mask)
# x = layers.LSTM(64)(x)
outputs = layers.Dense(4, activation="softmax")(x)
model_lstm2= tf.keras.Model(inputs, outputs)
model_lstm2.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_7 (InputLayer)        [(None, 211, 300)]        0         
                                                                 
 gru (GRU)                   (114, 64)                 70272     
                                                                 
 dense_3 (Dense)             (114, 4)                  260       
                                                                 
Total params: 70,532
Trainable params: 70,532
Non-trainable params: 0
_________________________________________________________________


In [49]:
model_lstm2.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model_lstm2.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5


2023-03-25 16:08:52.820913: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-03-25 16:08:53.187428: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


CancelledError: Graph execution error:

RecvAsync is cancelled.
	 [[{{node model_3/dense_3/Softmax/_20}}]] [Op:__inference_train_function_36100]

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()
model.add(LSTM(64, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dropout(0.2))
model.add(LSTM(64, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(64))
model.add(Dense(4, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])




Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2023-03-20 13:48:08.831618: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-20 13:48:08.831726: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


NameError: name 'X_train' is not defined

In [41]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.optimizers import Adam

model.compile(loss=SparseCategoricalCrossentropy(), optimizer=Adam(), metrics=["accuracy"])
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_33 (LSTM)              (None, 211, 64)           93440     
                                                                 
 lstm_34 (LSTM)              (None, 32)                12416     
                                                                 
 dense_7 (Dense)             (None, 4)                 132       
                                                                 
Total params: 105,988
Trainable params: 105,988
Non-trainable params: 0
_________________________________________________________________


In [42]:
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

Epoch 1/10


2023-03-18 02:36:51.372559: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-03-18 02:36:51.660659: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-03-18 02:36:51.934093: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-03-18 02:36:52.419899: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-03-18 02:36:53.015099: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


4/4 [==============================] - ETA: 0s - loss: 1.3853 - accuracy: 0.2353

2023-03-18 02:36:55.555320: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-03-18 02:36:55.667921: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-03-18 02:36:55.926320: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


4/4 [==============================] - 6s 863ms/step - loss: 1.3853 - accuracy: 0.2353 - val_loss: 1.3813 - val_accuracy: 0.3333
Epoch 2/10
4/4 [==============================] - 0s 108ms/step - loss: 1.3759 - accuracy: 0.3333 - val_loss: 1.3774 - val_accuracy: 0.3333
Epoch 3/10
4/4 [==============================] - 0s 99ms/step - loss: 1.3661 - accuracy: 0.3431 - val_loss: 1.3739 - val_accuracy: 0.3333
Epoch 4/10
4/4 [==============================] - 0s 101ms/step - loss: 1.3470 - accuracy: 0.3431 - val_loss: 1.3667 - val_accuracy: 0.3333
Epoch 5/10
4/4 [==============================] - 0s 101ms/step - loss: 1.3325 - accuracy: 0.3431 - val_loss: 1.3640 - val_accuracy: 0.3333
Epoch 6/10
4/4 [==============================] - 0s 101ms/step - loss: 1.3215 - accuracy: 0.3431 - val_loss: 1.4380 - val_accuracy: 0.3333
Epoch 7/10
4/4 [==============================] - 0s 102ms/step - loss: 1.2628 - accuracy: 0.4118 - val_loss: 2.1948 - val_accuracy: 0.1667
Epoch 8/10
4/4 [================

In [38]:
x = np.array([[4], [2]])

In [41]:
x.T.shape

(1, 2)

In [42]:
x.T

array([[4, 2]])