In [11]:
import tensorflow as tf
import os
import numpy as np
import pandas as pd

In [12]:
len(tf.config.list_physical_devices('GPU'))

1

In [13]:
def process_csv_file(file):
    try:
     csv_data = pd.read_csv(file)
    except:
         print("CANT READ CSV: ", file)
         return
    
    if csv_data.isnull().values.any():
            
            return False
    try:
        csv_data = csv_data.drop("class", axis = 1)
    except KeyError:
        pass
    return (csv_data.to_numpy())

In [4]:
!cd /Tmp/ASL-data/Database-augmented/coffee/; ls;
!ls

/bin/bash: line 1: cd: /Tmp/ASL-data/Database-augmented/coffee/: No such file or directory
 american-sign-language_1		   modelCNN.ipynb
'ASL Converter.code-workspace'		   modelYOLO.ipynb
 ASL_Language_translation.code-workspace   MS-ASL
 CNN_ASL_letters_1.h5			   NLP
 CNN_models				   README.md
 data_augmentation			   Report.docx
 frontend				   requirements.txt
 gitignore.txt				   tempCodeRunnerFile.python
 IMAGE_vision				   training_models
 main.py				   XINLEI_L_ALY_S_MRSTF_REPORT.docx
 american-sign-language_1		   modelCNN.ipynb
'ASL Converter.code-workspace'		   modelYOLO.ipynb
 ASL_Language_translation.code-workspace   MS-ASL
 CNN_ASL_letters_1.h5			   NLP
 CNN_models				   README.md
 data_augmentation			   Report.docx
 frontend				   requirements.txt
 gitignore.txt				   tempCodeRunnerFile.python
 IMAGE_vision				   training_models
 main.py				   XINLEI_L_ALY_S_MRSTF_REPORT.docx


In [14]:
file = "/Tmp/ASL-data/Database-augmented/test/coffee/2sGQuduhAf41354.csv"
process_csv_file(file)

array([[ 0.51505029,  0.337479  , -0.79841799, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.5149141 ,  0.33766055, -0.79397482, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.51484638,  0.33796486, -0.76542687, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.52175295,  0.3408646 , -0.72429359, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.52186459,  0.34013429, -0.74814087, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.52185893,  0.33947977, -0.76047277, ...,  0.        ,
         0.        ,  0.        ]])

In [15]:
def set_padding(arr, max_length):
    arr = np.append(arr, np.zeros((max_length-arr.shape[0],300)), axis=0)
    return np.expand_dims(arr, 0)

In [17]:
def prepare_data(folder_path, labels, train=True):
    total = 0
    max_length = 211
    
    # find max length
    # for folder in os.listdir(folder_path):
    #     print(folder)
    #     if folder != ".DS_Store":
    #         total += len(os.listdir(os.path.join(folder_path, folder)))
    #         for file in os.listdir(os.path.join(folder_path, folder)):
    #             if file != ".DS_Store":
    #                 data = process_csv_file(os.path.join(folder_path, folder, file))
    #                 if data is not(False):
    #                     if data.shape[0] > max_length:
    #                         max_length = data.shape[0]
    # print(max_length)
    # Make the arrays
    X = np.empty((0, max_length, 300))
    Y = np.empty((0,), int)
    print("----------")
    for folder in os.listdir(folder_path):
        print(folder)
        if folder != ".DS_Store":
            
            i=0
            for file in os.listdir(os.path.join(folder_path, folder)):
                if file != ".DS_Store": 
                    data = process_csv_file(os.path.join(folder_path, folder, file))
                    if data is not(False):
                        data = set_padding(data, max_length)
                        X = np.append(X, data, axis=0)
                        Y = np.append(Y, labels[folder])
                        if (i% 50 == 0):
                            print(i)
          
    print(total, max_length)
    return X, Y

In [23]:
folder_path_train = "/Tmp/ASL-data/Database-augmented/train"
labels= {"coffee": 0, 'dog': 1, 'milk': 2, 'door': 3}
X_train, Y_train = prepare_data(folder_path_train, labels)

----------
door
0
50
100
150
200
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
coffee
0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
milk
0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
dog
0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
0 211


In [24]:
folder_path_test = "/Tmp/ASL-data/Database-augmented/test"
labels = {"coffee": 0, 'dog': 1, 'milk': 2, 'door': 3}
X_test, Y_test = prepare_data(folder_path_test, labels, train=False)

----------
door
0
50
100
150
200
coffee
0
50
100
150
200
milk
0
50
100
150
200
dog
0
50
100
150
200
0 211


In [13]:
padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
    [
    [711, 632, 71],
    [73, 8, 3215, 55, 927],
    [83, 91, 1, 645, 1253, 927],
], padding="post"
)
# print(X[0][1])
print(((padded_inputs)))

[[ 711  632   71    0    0    0]
 [  73    8 3215   55  927    0]
 [  83   91    1  645 1253  927]]


In [24]:
# Y = np.expand_dims(Y, axis=0)
# Y= Y.T
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [25]:
# shuffle data
from sklearn.utils import shuffle

X_train,Y_train = shuffle(X_train, Y_train, random_state=0)
X_val,Y_val = shuffle(X_test, Y_test, random_state=0)
X_train, Y_train

(array([[[-0.35784977, -0.49811291, -0.58564818, ..., -0.56643144,
          -0.02385324,  0.        ],
         [-0.35082987, -0.49669157, -0.5180853 , ..., -0.5623646 ,
          -0.02286374,  0.        ],
         [-0.3494531 , -0.4982141 , -0.48567358, ..., -0.56411278,
          -0.02731383,  0.        ],
         ...,
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ]],
 
        [[-0.08607459, -0.36825343, -0.36514062, ..., -0.24118384,
          -0.05018822,  0.        ],
         [-0.08391427, -0.36187721, -0.45271721, ..., -0.21270907,
          -0.02258724,  0.        ],
         [ 0.14357082, -0.22242845, -0.61605823, ..., -0.46020831,
           0.        ,  0.        ],
         ...,
         [ 0.        ,  0.       

In [26]:
X_train.shape, Y_train.shape

((5117, 211, 300), (5117,))

In [27]:
x_shape = X_train.shape

In [87]:
from tensorflow.keras import layers
masking_input = []
for i in range(x_shape[0]):
    masking_input.append(X_train[i].T[0])

masking_input = np.array(masking_input)

masking_input.shape

(11060, 211)

In [20]:
embedding = layers.Embedding(input_dim=x_shape[1], output_dim=x_shape[1], mask_zero=True)
masked_output = embedding(masking_input)

print(masked_output._keras_mask)
masked_output
# masking_layer = layers.Masking()
# # Simulate the embedding lookup by expanding the 2D input to 3D,
# # with embedding dimension of 10.
# unmasked_embedding = tf.cast(
#     tf.tile(tf.expand_dims(padded_inputs, axis=-1), [1, 1, 10]), tf.float32
# )

# masked_embedding = masking_layer(unmasked_embedding)
# print(masked_embedding._keras_mask)

2023-04-21 00:13:36.221629: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-04-21 00:13:36.222041: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

tf.Tensor(
[[ True  True  True ... False False False]
 [ True  True  True ... False False False]
 [ True  True  True ... False False False]
 ...
 [ True  True  True ... False False False]
 [ True  True  True ... False False False]
 [ True  True  True ... False False False]], shape=(457, 211), dtype=bool)


<tf.Tensor: shape=(457, 211, 211), dtype=float32, numpy=
array([[[ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        ...,
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526]],

       [[ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        [ 0.04668217,  0.04604015,  0.01552759, ...,  0.0464903 ,
         -0.01109668, -0.01088526],
        ..

In [35]:
#LSTM model 
from tensorflow.keras import layers
x_shape = (457, 211, 300)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Flatten

model_lstm = Sequential()
model_lstm.add(LSTM(64, return_sequences=True, input_shape=(211, 300)))
model_lstm.add(Dropout(0.2))
model_lstm.add(LSTM(128, return_sequences=True))
model_lstm.add(Dropout(0.2))
model_lstm.add(LSTM(64))
model_lstm.add(Flatten())
model_lstm.add(Dense(128, activation="relu"))
model_lstm.add(Dense(64, activation="relu"))
model_lstm.add(Dense(4, activation='softmax'))


2023-06-17 01:00:53.189547: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-06-17 01:00:53.190430: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-06-17 01:00:53.191020: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

In [36]:
checkpoint = tf.keras.callbacks.ModelCheckpoint(
    "/Tmp/shariffa/LSTM-4-labels.{epoch:02d}-{val_accuracy:.2f}",
    monitor='val_accuracy',
    verbose=0,
    save_best_only=True,
    save_weights_only=False,
    mode='auto',
    save_freq='epoch',
)

In [37]:
model_lstm.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model_lstm.fit(X_train, Y_train, epochs=50, validation_data=(X_val, Y_val), callbacks=[checkpoint])

2023-06-17 01:00:57.319405: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 1295624400 exceeds 10% of free system memory.


Epoch 1/50


2023-06-17 01:00:58.271101: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-06-17 01:00:58.271901: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-06-17 01:00:58.272656: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

159/160 [============================>.] - ETA: 0s - loss: 1.1529 - accuracy: 0.4102

2023-06-17 01:01:05.276853: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-06-17 01:01:05.277765: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-06-17 01:01:05.278357: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

INFO:tensorflow:Assets written to: /Tmp/shariffa/LSTM-4-labels.01-0.37/assets


INFO:tensorflow:Assets written to: /Tmp/shariffa/LSTM-4-labels.01-0.37/assets


160/160 [==============================] - 13s 64ms/step - loss: 1.1513 - accuracy: 0.4102 - val_loss: 1.3906 - val_accuracy: 0.3722
Epoch 2/50
160/160 [==============================] - 5s 29ms/step - loss: 1.2902 - accuracy: 0.3234 - val_loss: 1.3860 - val_accuracy: 0.2544
Epoch 3/50
160/160 [==============================] - 5s 29ms/step - loss: 1.3270 - accuracy: 0.2834 - val_loss: 1.3940 - val_accuracy: 0.2544
Epoch 4/50
160/160 [==============================] - 5s 30ms/step - loss: 1.2930 - accuracy: 0.3264 - val_loss: 1.3387 - val_accuracy: 0.2570
Epoch 5/50
160/160 [==============================] - 5s 30ms/step - loss: 1.3223 - accuracy: 0.3269 - val_loss: 1.4291 - val_accuracy: 0.2532
Epoch 6/50
160/160 [==============================] - 5s 30ms/step - loss: 1.0170 - accuracy: 0.4784 - val_loss: 1.4393 - val_accuracy: 0.3544
Epoch 7/50
159/160 [============================>.] - ETA: 0s - loss: 0.9469 - accuracy: 0.4933

2023-06-17 01:01:39.412455: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-06-17 01:01:39.413338: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-06-17 01:01:39.413919: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

INFO:tensorflow:Assets written to: /Tmp/shariffa/LSTM-4-labels.07-0.51/assets


INFO:tensorflow:Assets written to: /Tmp/shariffa/LSTM-4-labels.07-0.51/assets


160/160 [==============================] - 10s 61ms/step - loss: 0.9478 - accuracy: 0.4931 - val_loss: 1.5236 - val_accuracy: 0.5114
Epoch 8/50
160/160 [==============================] - 5s 29ms/step - loss: 0.9102 - accuracy: 0.5157 - val_loss: 1.4958 - val_accuracy: 0.4266
Epoch 9/50
160/160 [==============================] - 5s 29ms/step - loss: 0.8491 - accuracy: 0.5392 - val_loss: 1.7753 - val_accuracy: 0.3924
Epoch 10/50
160/160 [==============================] - 5s 29ms/step - loss: 0.8105 - accuracy: 0.5533 - val_loss: 1.2851 - val_accuracy: 0.4481
Epoch 11/50
160/160 [==============================] - 5s 29ms/step - loss: 0.7840 - accuracy: 0.5650 - val_loss: 1.1323 - val_accuracy: 0.4911
Epoch 12/50
160/160 [==============================] - 5s 29ms/step - loss: 0.7158 - accuracy: 0.6058 - val_loss: 1.1196 - val_accuracy: 0.4949
Epoch 13/50
160/160 [==============================] - ETA: 0s - loss: 0.7176 - accuracy: 0.5966

2023-06-17 01:02:12.423692: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-06-17 01:02:12.424581: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-06-17 01:02:12.425199: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

INFO:tensorflow:Assets written to: /Tmp/shariffa/LSTM-4-labels.13-0.59/assets


INFO:tensorflow:Assets written to: /Tmp/shariffa/LSTM-4-labels.13-0.59/assets


160/160 [==============================] - 10s 60ms/step - loss: 0.7176 - accuracy: 0.5966 - val_loss: 1.3374 - val_accuracy: 0.5861
Epoch 14/50
160/160 [==============================] - 5s 29ms/step - loss: 0.6682 - accuracy: 0.6330 - val_loss: 1.4121 - val_accuracy: 0.4975
Epoch 15/50
160/160 [==============================] - 5s 30ms/step - loss: 0.6604 - accuracy: 0.6416 - val_loss: 1.4445 - val_accuracy: 0.5506
Epoch 16/50
160/160 [==============================] - 5s 30ms/step - loss: 0.6196 - accuracy: 0.6828 - val_loss: 1.5746 - val_accuracy: 0.4734
Epoch 17/50
160/160 [==============================] - 5s 30ms/step - loss: 0.5570 - accuracy: 0.7186 - val_loss: 1.2717 - val_accuracy: 0.5443
Epoch 18/50
159/160 [============================>.] - ETA: 0s - loss: 0.5266 - accuracy: 0.7419

2023-06-17 01:02:40.887679: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-06-17 01:02:40.888662: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-06-17 01:02:40.889261: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

INFO:tensorflow:Assets written to: /Tmp/shariffa/LSTM-4-labels.18-0.63/assets


INFO:tensorflow:Assets written to: /Tmp/shariffa/LSTM-4-labels.18-0.63/assets


160/160 [==============================] - 10s 60ms/step - loss: 0.5262 - accuracy: 0.7420 - val_loss: 1.1698 - val_accuracy: 0.6253
Epoch 19/50
160/160 [==============================] - 5s 29ms/step - loss: 0.4453 - accuracy: 0.7694 - val_loss: 1.3393 - val_accuracy: 0.6089
Epoch 20/50
159/160 [============================>.] - ETA: 0s - loss: 0.3365 - accuracy: 0.8243

2023-06-17 01:02:55.199960: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-06-17 01:02:55.201029: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-06-17 01:02:55.201657: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

INFO:tensorflow:Assets written to: /Tmp/shariffa/LSTM-4-labels.20-0.71/assets


INFO:tensorflow:Assets written to: /Tmp/shariffa/LSTM-4-labels.20-0.71/assets


160/160 [==============================] - 10s 61ms/step - loss: 0.3362 - accuracy: 0.8243 - val_loss: 1.0476 - val_accuracy: 0.7089
Epoch 21/50
160/160 [==============================] - 5s 30ms/step - loss: 0.2770 - accuracy: 0.8556 - val_loss: 1.3339 - val_accuracy: 0.6443
Epoch 22/50
160/160 [==============================] - 5s 29ms/step - loss: 0.2920 - accuracy: 0.8540 - val_loss: 1.2318 - val_accuracy: 0.5886
Epoch 23/50
160/160 [==============================] - 5s 29ms/step - loss: 0.2537 - accuracy: 0.8603 - val_loss: 1.7999 - val_accuracy: 0.5620
Epoch 24/50
160/160 [==============================] - 5s 30ms/step - loss: 0.2215 - accuracy: 0.8874 - val_loss: 2.1128 - val_accuracy: 0.5089
Epoch 25/50
160/160 [==============================] - 5s 30ms/step - loss: 0.2763 - accuracy: 0.8853 - val_loss: 1.3731 - val_accuracy: 0.5342
Epoch 26/50
160/160 [==============================] - 5s 30ms/step - loss: 0.1719 - accuracy: 0.9320 - val_loss: 2.1077 - val_accuracy: 0.5810
Epo

In [ ]:
inputs = layers.Input(shape=(x_shape[1], x_shape[2]))
x = layers.GRU(64)(inputs, mask=masked_output._keras_mask)
# x = layers.LSTM(64)(x)
outputs = layers.Dense(4, activation="softmax")(x)
model_lstm2= tf.keras.Model(inputs, outputs)
model_lstm2.summary()

In [ ]:
model_lstm2.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model_lstm2.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()
model.add(LSTM(64, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dropout(0.2))
model.add(LSTM(64, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(64))
model.add(Dense(4, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])



In [ ]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.optimizers import Adam

model.compile(loss=SparseCategoricalCrossentropy(), optimizer=Adam(), metrics=["accuracy"])
model.summary()

In [ ]:
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)